services:
  qiita-trend-front:
    container_name: qiita-trend-front
    build:
      context: .
      dockerfile: ./apps/qiita-trend-front/Dockerfile
    profiles:
      - frontend
    restart: always
    ports:
      - "3000:3000"
  qiita-trend-backend:
    container_name: qiita-trend-backend
    build:
      context: .
      dockerfile: ./apps/qiita-trend-backend/Dockerfile
    profiles:
      - backend
    restart: always
    ports:
      - "3200:3200"
  db:
    container_name: db
    image: postgres:18@sha256:7e32e9833a6fb1c92c32552794cb6ed569d51b445a54907d35fc112ef39684db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  redis:
    image: redis:8.6@sha256:4d25e2fe601f7ffaeb4437cb6ced3518bc36edf34ebe98863c80836943d94529
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --protected-mode yes
      --requirepass password
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always
volumes:
  postgres_data:
  redis-data: