name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: "docker buildxが使えるようにする"
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3
      - name: "ghcr.ioにログインする"
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "メタデータを作成する"
        id: meta # 後段で参照できるようにoutputsに登録する
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            org.opencontainers.image.title=sample-app
            org.opencontainers.image.vendor="AP Communications Co.,Ltd."
            org.opencontainers.image.licenses=Apache-2.0
      - name: "コンテナイメージをビルドしてghcr.ioにコンテナイメージをpushする"
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6
        with:
          file: ../Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # 前ステップで設定したタグを参照する
          labels: ${{ steps.meta.outputs.labels }} # 前ステップで設定したラベルを参照する
