name: Docker Image Cd

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: "docker buildxが使えるようにする"
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      - name: "ghcr.ioにログインする"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "メタデータを作成する"
        id: meta # 後段で参照できるようにoutputsに登録する
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            org.opencontainers.image.title=sample-app
            org.opencontainers.image.vendor="AP Communications Co.,Ltd."
            org.opencontainers.image.licenses=Apache-2.0
      - name: "コンテナイメージをビルドしてghcr.ioにコンテナイメージをpushする"
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          file: ./apps/qiita-trend-front/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # 前ステップで設定したタグを参照する
          labels: ${{ steps.meta.outputs.labels }} # 前ステップで設定したラベルを参照する
          ssh: |
            default
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: "docker buildxが使えるようにする"
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
      - name: "ghcr.ioにログインする"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "メタデータを作成する"
        id: meta # 後段で参照できるようにoutputsに登録する
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            org.opencontainers.image.title=sample-app
            org.opencontainers.image.vendor="AP Communications Co.,Ltd."
            org.opencontainers.image.licenses=Apache-2.0
      - name: "コンテナイメージをビルドしてghcr.ioにコンテナイメージをpushする"
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          file: ./apps/qiita-trend-backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # 前ステップで設定したタグを参照する
          labels: ${{ steps.meta.outputs.labels }} # 前ステップで設定したラベルを参照する
          ssh: |
            default

