name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: "docker buildxが使えるようにする"
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
      - name: "ghcr.ioにログインする"
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "メタデータを作成する"
        id: meta # 後段で参照できるようにoutputsに登録する
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
          labels: |
            org.opencontainers.image.title=sample-app
            org.opencontainers.image.vendor="AP Communications Co.,Ltd."
            org.opencontainers.image.licenses=Apache-2.0
      - name: "コンテナイメージをビルドしてghcr.ioにコンテナイメージをpushする"
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
        with:
          file: ../Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # 前ステップで設定したタグを参照する
          labels: ${{ steps.meta.outputs.labels }} # 前ステップで設定したラベルを参照する
